import type { Category, DeliveryArea, MenuItem, Order, Review } from "@/lib/types";

export const categories: Category[] = [
  {
    id: "handi-karahi",
    name: "Handi & Karahi",
    slug: "handi-karahi",
    description: "Slow-cooked gravies with naan, roti, and family portions."
  },
  {
    id: "chapli-burger",
    name: "Chapli Burger",
    slug: "chapli-burger",
    description: "Chapli patties with Single and Twin Tower double-patty options."
  },
  {
    id: "zinger",
    name: "Zinger",
    slug: "zinger",
    description: "Crispy chicken burgers, including the Double Decker."
  },
  {
    id: "wraps",
    name: "Wraps",
    slug: "wraps",
    description: "Portable favorites for solo cravings and late-night orders."
  },
  {
    id: "appetizers",
    name: "Appetizers",
    slug: "appetizers",
    description: "Fries, pasta, chicken strips, dips, and crunchy sides."
  },
  {
    id: "golden-nuggets",
    name: "Golden Nuggets",
    slug: "golden-nuggets",
    description: "Injected Al-Baik-style and skin-on Tempura nugget varieties."
  },
  {
    id: "chunky-chicken",
    name: "Chunky Chicken",
    slug: "chunky-chicken",
    description: "Crispy chicken chunks with dipping sauce."
  },
  {
    id: "wings",
    name: "Wings",
    slug: "wings",
    description: "Masala wings with green chutney and plain baked wings."
  },
  {
    id: "deals",
    name: "Deals",
    slug: "deals",
    description: "Solo, buddy, family, couple, and midnight bundles."
  },
  {
    id: "breads-drinks",
    name: "Breads & Drinks",
    slug: "breads-drinks",
    description: "Fresh roti, milky naan, cold drinks, and add-ons."
  },
  {
    id: "tea",
    name: "Tea",
    slug: "tea",
    description: "Karak doodh patti, cardamom, ginger, and Zaiqa special tea."
  }
];

export const menuItems: MenuItem[] = [
  {
    id: "velvety-shahi-handi",
    categoryId: "handi-karahi",
    name: "Velvety Shahi Handi",
    slug: "velvety-shahi-handi",
    description: "Creamy homemade chicken handi — choose Half or Full portion.",
    price: 1199,
    image: "/images/menu/shahi-handi-clean.webp",
    popular: true,
    tags: ["Gravy", "Best seller", "Dinner"],
    mealTime: "dinner",
    spiceLevel: "medium",
    prepTime: 40,
    available: true,
    optionsHint: "Half / Full",
    options: [
      { id: "half", label: "Half (500g)", price: 1199, hintLabel: "Half" },
      { id: "full", label: "Full (1kg)", price: 2199, hintLabel: "Full" }
    ]
  },

  {
    id: "royal-gola-kabab-half",
    categoryId: "handi-karahi",
    name: "Royal Gola Kabab Bowl Half",
    slug: "royal-gola-kabab-half",
    description: "Tender gola kabab in a rich creamy bowl, built for sharing.",
    price: 1299,
    image: "/images/menu/gola-kabab-clean.webp",
    popular: false,
    tags: ["Kabab", "Dinner"],
    mealTime: "dinner",
    spiceLevel: "medium",
    prepTime: 35,
    available: true
  },
  {
    id: "eco-crunch-patty-burger",
    categoryId: "zinger",
    name: "Eco Crunch Patty Burger",
    slug: "eco-crunch-patty-burger",
    description: "Juicy chicken breast with house-made sauce in a toasted bun.",
    price: 249,
    image: "/images/menu/eco-crunch-patty.jpg",
    popular: true,
    tags: ["Burger", "Crunchy", "Quick bite"],
    mealTime: "lunch",
    spiceLevel: "medium",
    prepTime: 18,
    available: true,
    variantLabel: "Crunchy Patty"
  },
  {
    id: "zinger-booster",
    categoryId: "zinger",
    name: "Zinger Booster",
    slug: "zinger-booster",
    description: "Crispy zinger chicken, lettuce, and creamy house sauce.",
    price: 299,
    image: "/images/menu/zinger-burger.webp",
    popular: true,
    tags: ["Zinger", "Best seller"],
    mealTime: "dinner",
    spiceLevel: "hot",
    prepTime: 20,
    available: true,
    variantLabel: "Classic Zinger"
  },
  {
    id: "zaiqa-double-decker",
    categoryId: "zinger",
    name: "Zaiqa Double Decker",
    slug: "zaiqa-double-decker",
    description: "Two crispy zinger layers with cheese-style sauce and crunchy lettuce.",
    price: 599,
    image: "/images/menu/double-decker.webp",
    popular: false,
    tags: ["Burger", "Loaded", "Double Decker"],
    mealTime: "dinner",
    spiceLevel: "hot",
    prepTime: 24,
    available: true,
    variantLabel: "Double Decker"
  },
  {
    id: "zaiqa-chapligar",
    categoryId: "chapli-burger",
    name: "Zaiqa Chapligar",
    slug: "zaiqa-chapligar",
    description: "Traditional chapli patty with fresh spices and house sauce.",
    price: 249,
    image: "/images/menu/eco-crunch.webp",
    popular: false,
    tags: ["Burger", "Chapli", "Patty"],
    mealTime: "lunch",
    spiceLevel: "medium",
    prepTime: 18,
    available: true,
    variantLabel: "Single"
  },
  {
    id: "zaiqa-chapligar-twin-tower",
    categoryId: "chapli-burger",
    name: "Zaiqa Chapligar Twin Tower",
    slug: "zaiqa-chapligar-twin-tower",
    description: "Double chapli patties stacked with cheese-style sauce and fresh toppings.",
    price: 449,
    image: "/images/menu/burger-plate.webp",
    popular: false,
    tags: ["Burger", "Chapli", "Twin Tower", "Double Patty"],
    mealTime: "dinner",
    spiceLevel: "medium",
    prepTime: 22,
    available: true,
    variantLabel: "Twin Tower"
  },
  {
    id: "zaiqa-wrap",
    categoryId: "wraps",
    name: "Zaiqa Wrap",
    slug: "zaiqa-wrap",
    description: "Soft wrap packed with crispy chicken, greens, and house sauce.",
    price: 399,
    image: "/images/menu/zaiqa-wrap.jpg",
    popular: false,
    tags: ["Wrap", "Lunch"],
    mealTime: "lunch",
    spiceLevel: "medium",
    prepTime: 18,
    available: true
  },
  {
    id: "king-crunch-wrap",
    categoryId: "wraps",
    name: "King Crunch Wrap",
    slug: "king-crunch-wrap",
    description: "A bigger wrap with extra crunch, sauce, and late-night energy.",
    price: 599,
    image: "/images/menu/king-crunch-wrap.jpg",
    popular: true,
    tags: ["Wrap", "Popular", "Midnight"],
    mealTime: "dinner",
    spiceLevel: "hot",
    prepTime: 22,
    available: true
  },
  {
    id: "salty-plain-fries",
    categoryId: "appetizers",
    name: "Salty Plain Fries",
    slug: "salty-plain-fries",
    description: "Classic crisp fries, lightly salted.",
    price: 199,
    image: "/images/menu/salty-plain-fries.webp",
    popular: false,
    tags: ["Fries", "Snack"],
    mealTime: "lunch",
    spiceLevel: "mild",
    prepTime: 14,
    available: true,
    optionsHint: "Half / Full",
    options: [
      { id: "half", label: "Half", price: 199 },
      { id: "full", label: "Full", price: 349 }
    ]
  },
  {
    id: "golden-hot-masala-fries",
    categoryId: "appetizers",
    name: "Golden Hot Masala Fries",
    slug: "golden-hot-masala-fries",
    description: "Crisp fries tossed in hot masala with house dip.",
    price: 249,
    image: "/images/menu/masala-fries.webp",
    popular: true,
    tags: ["Fries", "Spicy", "Snack"],
    mealTime: "lunch",
    spiceLevel: "hot",
    prepTime: 14,
    available: true,
    optionsHint: "Half / Full",
    options: [
      { id: "half", label: "Half", price: 249 },
      { id: "full", label: "Full", price: 349 }
    ]
  },
  {
    id: "legend-loaded-fries",
    categoryId: "appetizers",
    name: "The Legend Loaded Fries",
    slug: "legend-loaded-fries",
    description: "Loaded fries layered with sauce, chicken bites, and spice.",
    price: 299,
    image: "/images/menu/loaded-fries.webp",
    popular: true,
    tags: ["Loaded", "Best seller", "Fries"],
    mealTime: "lunch",
    spiceLevel: "hot",
    prepTime: 18,
    available: true,
    optionsHint: "Half / Full",
    options: [
      { id: "half", label: "Half", price: 299 },
      { id: "full", label: "Full", price: 499 }
    ]
  },
  {
    id: "creamy-silky-pasta",
    categoryId: "appetizers",
    name: "Creamy Silky Pasta",
    slug: "creamy-silky-pasta",
    description: "Creamy silky pasta with a rich white sauce.",
    price: 299,
    image: "/images/menu/creamy-silky-pasta.jpg",
    popular: false,
    tags: ["Pasta", "Creamy"],
    mealTime: "lunch",
    spiceLevel: "mild",
    prepTime: 20,
    available: true,
    optionsHint: "Half / Full",
    options: [
      { id: "half", label: "Half", price: 299 },
      { id: "full", label: "Full", price: 549 }
    ]
  },
  {
    id: "creamy-spicy-pasta",
    categoryId: "appetizers",
    name: "Creamy Spicy Pasta",
    slug: "creamy-spicy-pasta",
    description: "Creamy pasta with a bold, spicy sauce.",
    price: 299,
    image: "/images/menu/creamy-spicy-pasta.jpg",
    popular: false,
    tags: ["Pasta", "Spicy"],
    mealTime: "lunch",
    spiceLevel: "hot",
    prepTime: 20,
    available: true,
    optionsHint: "Half / Full",
    options: [
      { id: "half", label: "Half", price: 299 },
      { id: "full", label: "Full", price: 549 }
    ]
  },
  {
    id: "injected-nuggets",
    categoryId: "golden-nuggets",
    name: "Injected Nuggets",
    slug: "injected-nuggets",
    description: "Al-Baik style injected nuggets with a crisp coating and tender center.",
    price: 249,
    image: "/images/whatsapp/zaiqa-09.jpg",
    popular: false,
    tags: ["Nuggets", "Injected", "Al-Baik style"],
    mealTime: "lunch",
    spiceLevel: "mild",
    prepTime: 16,
    available: true,
    variantLabel: "Injected",
    optionsHint: "3 / 6 / 12 pcs",
    options: [
      { id: "3pc", label: "3 Pieces", price: 249 },
      { id: "6pc", label: "6 Pieces", price: 449 },
      { id: "12pc", label: "12 Pieces", price: 899 }
    ]
  },
  {
    id: "tempura-nuggets",
    categoryId: "golden-nuggets",
    name: "Tempura Nuggets",
    slug: "tempura-nuggets",
    description: "Skin-on tempura nuggets with a light, crunchy coating.",
    price: 249,
    image: "/images/menu/tempura-nuggets.jpg",
    popular: false,
    tags: ["Nuggets", "Tempura", "Skin-on"],
    mealTime: "lunch",
    spiceLevel: "mild",
    prepTime: 16,
    available: true,
    variantLabel: "Tempura",
    optionsHint: "4 / 8 / 12 pcs",
    options: [
      { id: "4pc", label: "4 Pieces", price: 249 },
      { id: "8pc", label: "8 Pieces", price: 549 },
      { id: "12pc", label: "12 Pieces", price: 849 }
    ]
  },
  {
    id: "crispy-chicken-strips",
    categoryId: "appetizers",
    name: "Crispy Chicken Strips",
    slug: "crispy-chicken-strips",
    description: "Crispy golden chicken breast strips with dipping sauce.",
    price: 399,
    image: "/images/menu/chicken-strips.webp",
    popular: false,
    tags: ["Strips", "Crispy", "Chicken"],
    mealTime: "lunch",
    spiceLevel: "medium",
    prepTime: 18,
    available: true,
    optionsHint: "4 / 8 pcs",
    options: [
      { id: "4pc", label: "4 Pieces", price: 399 },
      { id: "8pc", label: "8 Pieces", price: 749 }
    ]
  },
  {
    id: "dip-sauce",
    categoryId: "appetizers",
    name: "Dip Sauce",
    slug: "dip-sauce",
    description: "House-made dipping sauce for nuggets, strips, and fries.",
    price: 69,
    image: "/images/whatsapp/zaiqa-13.jpg",
    popular: false,
    tags: ["Dip", "Sauce", "Add-on"],
    mealTime: "lunch",
    spiceLevel: "mild",
    prepTime: 5,
    available: true
  },
  {
    id: "chunky-chicken-12pc",
    categoryId: "chunky-chicken",
    name: "Chunky Chicken 12 Pieces",
    slug: "chunky-chicken-12pc",
    description: "Twelve crispy chicken chunks with a dipping sauce.",
    price: 499,
    image: "/images/whatsapp/zaiqa-12.jpg",
    popular: true,
    tags: ["Chunky", "Shareable", "12 Pcs"],
    mealTime: "lunch",
    spiceLevel: "medium",
    prepTime: 20,
    available: true
  },
  {
    id: "masala-wings",
    categoryId: "wings",
    name: "Masala Wings",
    slug: "masala-wings",
    description: "Masala wings served with green chutney.",
    price: 299,
    image: "/images/menu/masala-wings.jpg",
    popular: true,
    tags: ["Wings", "Masala", "Green Chutney"],
    mealTime: "dinner",
    spiceLevel: "hot",
    prepTime: 22,
    available: true,
    variantLabel: "Masala Wings",
    optionsHint: "4 / 8 pcs",
    options: [
      { id: "4pc", label: "4 Pieces", price: 299 },
      { id: "8pc", label: "8 Pieces", price: 599 }
    ]
  },
  {
    id: "plain-baked-wings",
    categoryId: "wings",
    name: "Baked Wings",
    slug: "plain-baked-wings",
    description: "Plain baked wings with a crisp, seasoned finish.",
    price: 299,
    image: "/images/menu/baked-wings-plain.jpg",
    popular: false,
    tags: ["Wings", "Baked", "Plain"],
    mealTime: "dinner",
    spiceLevel: "medium",
    prepTime: 22,
    available: true,
    variantLabel: "Baked Wings",
    optionsHint: "4 / 8 pcs",
    options: [
      { id: "4pc", label: "4 Pieces", price: 299 },
      { id: "8pc", label: "8 Pieces", price: 599 }
    ]
  },
  {
    id: "solo-handi-deal",
    categoryId: "deals",
    name: "Solo Handi Deal",
    slug: "solo-handi-deal",
    description: "Quarter Handi (250g) + 2 Milky Naan + 1 Buddy Drink (350ml).",
    price: 649,
    image: "/images/menu/deal-solo-handi-v2.jpg",
    popular: true,
    tags: ["Deal", "Solo", "Handi", "Naan", "Drink"],
    mealTime: "dinner",
    spiceLevel: "medium",
    prepTime: 32,
    available: true,
    handi_quantity: 1,
    handi_size: "250g",
    appetizer_count: 0,
    appetizer_types: [],
    naan_quantity: 2,
    drink_volume_ml: 350,
    free_items: []
  },
  {
    id: "solo-zinger-deal",
    categoryId: "deals",
    name: "Solo Zinger Deal",
    slug: "solo-zinger-deal",
    description: "1 Zinger Booster + Half Golden Hot Masala Fries + 1 Drink (350ml).",
    price: 549,
    image: "/images/menu/deal-solo-zinger-v2.jpg",
    popular: true,
    tags: ["Deal", "Solo", "Zinger", "Fries", "Drink"],
    mealTime: "dinner",
    spiceLevel: "hot",
    prepTime: 22,
    available: true,
    handi_quantity: 0,
    handi_size: "",
    appetizer_count: 1,
    appetizer_types: ["Golden Hot Masala Fries (Half serving)"],
    naan_quantity: 0,
    drink_volume_ml: 350,
    free_items: []
  },
  {
    id: "happy-family-deal",
    categoryId: "deals",
    name: "Happy Family Deal",
    slug: "happy-family-deal",
    description: "Half Velvety Shahi Handi (500g) + 8 Injected Nuggets + 12 Baked Wings + 6 Milky Naan + 1.5 Ltr Drink + Free Zinger Booster.",
    price: 2899,
    image: "/images/menu/deal-happy-family-v2.jpg",
    popular: true,
    tags: ["Deal", "Family", "Handi", "Nuggets", "Wings", "Naan", "Drink", "Free Zinger"],
    mealTime: "dinner",
    spiceLevel: "medium",
    prepTime: 48,
    available: true,
    handi_quantity: 1,
    handi_size: "500g",
    appetizer_count: 20,
    appetizer_types: ["Injected Nuggets (8 pieces)", "Baked Wings (12 pieces)"],
    naan_quantity: 6,
    drink_volume_ml: 1500,
    free_items: ["Zinger Booster"]
  },
  {
    id: "buddy-deal",
    categoryId: "deals",
    name: "Buddy Deal",
    slug: "buddy-deal",
    description: "2 Zinger Boosters + Half Golden Hot Masala Fries + 2 Buddy Drinks (350ml each).",
    price: 949,
    image: "/images/menu/deal-buddy-v2.jpg",
    popular: false,
    tags: ["Deal", "Two people", "Zinger", "Fries", "Drinks"],
    mealTime: "dinner",
    spiceLevel: "hot",
    prepTime: 28,
    available: true,
    handi_quantity: 0,
    handi_size: "",
    appetizer_count: 1,
    appetizer_types: ["Golden Hot Masala Fries (Half serving)"],
    naan_quantity: 0,
    drink_volume_ml: 700,
    free_items: []
  },
  {
    id: "midnight-sharing-deal",
    categoryId: "deals",
    name: "Midnight Sharing Deal",
    slug: "midnight-sharing-deal",
    description: "2 Zaiqa Wraps + 2 Buddy Drinks (350ml each). Available 11 PM to 1 AM.",
    price: 949,
    image: "/images/menu/deal-midnight-sharing-v2.jpg",
    popular: false,
    tags: ["Deal", "Midnight", "Shareable", "Wrap", "Drinks"],
    mealTime: "dinner",
    spiceLevel: "medium",
    prepTime: 24,
    available: true,
    handi_quantity: 0,
    handi_size: "",
    appetizer_count: 0,
    appetizer_types: [],
    naan_quantity: 0,
    drink_volume_ml: 700,
    free_items: []
  },
  {
    id: "couple-deal",
    categoryId: "deals",
    name: "Couple Deal",
    slug: "couple-deal",
    description: "2 Tempura Nuggets + 2 Injected Nuggets + 4 Baked Wings + Regular Fries + 2 Karak Doodh Patti or Drinks.",
    price: 899,
    image: "/images/menu/deal-couple.jpg",
    popular: false,
    tags: ["Deal", "Couple", "Nuggets", "Wings", "Fries", "Tea", "Drink"],
    mealTime: "dinner",
    spiceLevel: "medium",
    prepTime: 30,
    available: true,
    handi_quantity: 0,
    handi_size: "",
    appetizer_count: 9,
    appetizer_types: [
      "Tempura Nuggets (2 pieces)",
      "Injected Nuggets (2 pieces)",
      "Baked Wings (4 pieces)",
      "Regular Fries (1 serving)"
    ],
    naan_quantity: 0,
    drink_volume_ml: 700,
    free_items: []
  },
  {
    id: "milky-naan",
    categoryId: "breads-drinks",
    name: "Milky Naan",
    slug: "milky-naan",
    description: "Soft naan for pairing with handi and karahi orders.",
    price: 50,
    image: "/images/menu/milky-naan-v2.png",
    popular: false,
    tags: ["Bread", "Add-on", "Naan"],
    mealTime: "dinner",
    spiceLevel: "mild",
    prepTime: 8,
    available: true
  },
  {
    id: "drink-350ml",
    categoryId: "breads-drinks",
    name: "Drink (350ml)",
    slug: "drink-350ml",
    description: "Cold soft drink in a 350ml bottle.",
    price: 80,
    image: "/images/menu/drink-350ml-v2.jpg",
    popular: false,
    tags: ["Drink", "Cold", "Add-on"],
    mealTime: "lunch",
    spiceLevel: "mild",
    prepTime: 2,
    available: true
  },
  {
    id: "zaiqa-doodh-patti",
    categoryId: "tea",
    name: "Zaiqa Doodh Patti",
    slug: "zaiqa-doodh-patti",
    description: "Rich karak doodh patti brewed with milk and tea leaves.",
    price: 120,
    image: "/images/whatsapp/zaiqa-04.jpg",
    popular: false,
    tags: ["Tea", "Doodh Patti", "Karak", "Hot"],
    mealTime: "beverages",
    spiceLevel: "mild",
    prepTime: 10,
    available: true
  },
  {
    id: "cardamom-tea",
    categoryId: "tea",
    name: "Cardamom Tea",
    slug: "cardamom-tea",
    description: "Warm cardamom chai for pickup or evening delivery orders.",
    price: 120,
    image: "/images/whatsapp/zaiqa-05.jpg",
    popular: false,
    tags: ["Tea", "Cardamom", "Chai", "Hot"],
    mealTime: "beverages",
    spiceLevel: "mild",
    prepTime: 10,
    available: true
  },
  {
    id: "zaiqa-tea",
    categoryId: "tea",
    name: "Zaiqa Tea",
    slug: "zaiqa-tea",
    description: "Zaiqa special tea with a unique house blend.",
    price: 120,
    image: "/images/whatsapp/zaiqa-06.jpg",
    popular: false,
    tags: ["Tea", "Special", "Zaiqa", "Hot"],
    mealTime: "beverages",
    spiceLevel: "mild",
    prepTime: 10,
    available: true
  },
  {
    id: "ginger-tea",
    categoryId: "tea",
    name: "Ginger Tea",
    slug: "ginger-tea",
    description: "Fresh ginger tea with a warm, spicy kick.",
    price: 120,
    image: "/images/whatsapp/zaiqa-07.jpg",
    popular: false,
    tags: ["Tea", "Ginger", "Chai", "Hot"],
    mealTime: "beverages",
    spiceLevel: "mild",
    prepTime: 10,
    available: true
  }
];

export const deliveryAreas: DeliveryArea[] = [
  {
    id: "near-kitchen",
    name: "Near kitchen / Shah Rukn E Alam",
    fee: 80,
    eta: "20-30 min",
    minimumOrder: 499,
    active: true
  },
  {
    id: "gulgasht-bosan",
    name: "Gulgasht / Bosan Road",
    fee: 120,
    eta: "30-40 min",
    minimumOrder: 599,
    active: true
  },
  {
    id: "multan-cantt",
    name: "Cantt / Multan City",
    fee: 150,
    eta: "35-45 min",
    minimumOrder: 699,
    active: true
  },
  {
    id: "wapda-bahadurpur",
    name: "WAPDA Town / Bahadurpur",
    fee: 180,
    eta: "40-50 min",
    minimumOrder: 799,
    active: true
  },
  {
    id: "other-area",
    name: "Other Multan area - confirm on WhatsApp",
    fee: 0,
    eta: "Delivery fee confirmed on WhatsApp",
    minimumOrder: 0,
    active: true
  },
  {
    id: "pickup",
    name: "Pickup - Zaiqa Junction With Zahra's",
    fee: 0,
    eta: "Ready in 20-30 min",
    minimumOrder: 0,
    active: true
  }
];

export const reviews: Review[] = [
  {
    id: "review-1",
    name: "Areeba K.",
    rating: 5,
    quote: "The Shahi Handi tasted homemade but packed like a premium order. Naan arrived soft and warm.",
    source: "WhatsApp",
    image: "/images/menu/shahi-handi-clean.webp",
    createdAt: "2026-05-29T18:45:00.000Z",
    approved: true
  },
  {
    id: "review-2",
    name: "Hamza M.",
    rating: 5,
    quote: "Zinger Booster and loaded fries were better than my usual delivery app order. Direct WhatsApp confirmation was fast.",
    source: "Website",
    image: "/images/menu/zinger-burger.webp",
    createdAt: "2026-05-31T21:10:00.000Z",
    approved: true
  },
  {
    id: "review-3",
    name: "Nimra S.",
    rating: 5,
    quote: "Family deal was enough for everyone and the gravy had that fresh kitchen flavor.",
    source: "Foodpanda",
    image: "/images/menu/shahi-handi-clean.webp",
    createdAt: "2026-06-02T20:18:00.000Z",
    approved: true
  },
  {
    id: "review-4",
    name: "Bilal R.",
    rating: 4,
    quote: "Masala fries were crisp, spicy, and still hot when delivered. Will order again.",
    source: "Instagram",
    image: "/images/menu/masala-fries.webp",
    createdAt: "2026-06-03T23:35:00.000Z",
    approved: true
  }
];

export const seedOrders: Order[] = [
  {
    id: "ZQ-DEMO-101",
    customerName: "Demo Customer",
    phone: "0312-0000000",
    address: "Shah Rukn E Alam Town, Multan",
    deliveryAreaId: "near-kitchen",
    deliveryAreaName: "Near kitchen / Shah Rukn E Alam",
    deliveryFee: 120,
    items: [
      {
        lineId: "demo-1",
        menuItemId: "zinger-booster",
        name: "Zinger Booster",
        basePrice: 299,
        price: 299,
        quantity: 2,
        addons: []
      },
      {
        lineId: "demo-2",
        menuItemId: "legend-loaded-fries-full",
        name: "The Legend Loaded Fries Full",
        basePrice: 499,
        price: 499,
        quantity: 1,
        addons: []
      }
    ],
    subtotal: 1097,
    discount: 0,
    total: 1217,
    loyaltyPointsEarned: 12,
    paymentMethod: "cash_on_delivery",
    status: "preparing",
    createdAt: "2026-06-05T17:45:00.000Z"
  }
];
