import type { Category, DeliveryArea, MenuItem, Order, Review } from "@/lib/types";

export const categories: Category[] = [
  {
    id: "handi-karahi",
    name: "Handi & Karahi",
    slug: "handi-karahi",
    description: "Slow-cooked gravies with naan, roti, and family portions."
  },
  {
    id: "chapli-burgers",
    name: "Chapli Burgers",
    slug: "chapli-burgers",
    description: "Traditional chapli patties with fresh spices and house sauce."
  },
  {
    id: "crunchy-burger",
    name: "Crunchy Burger",
    slug: "crunchy-burger",
    description: "Crispy chicken, house sauce, and fresh buns."
  },
  {
    id: "wraps",
    name: "Wraps",
    slug: "wraps",
    description: "Portable favorites for solo cravings and late-night orders."
  },
  {
    id: "appetizers",
    name: "Appetizers",
    slug: "appetizers",
    description: "Fries, nuggets, strips, dips, and crunchy sides."
  },
  {
    id: "chunky-chicken",
    name: "Chunky Chicken",
    slug: "chunky-chicken",
    description: "Crispy chicken chunks with dipping sauce."
  },
  {
    id: "wings",
    name: "Wings",
    slug: "wings",
    description: "Masala wings with green chutney and plain baked wings."
  },
  {
    id: "deals",
    name: "Deals",
    slug: "deals",
    description: "Solo, buddy, family, couple, and midnight bundles."
  },
  {
    id: "breads-drinks",
    name: "Breads & Drinks",
    slug: "breads-drinks",
    description: "Fresh roti, milky naan, cold drinks, and add-ons."
  },
  {
    id: "tea",
    name: "Tea",
    slug: "tea",
    description: "Karak doodh patti, cardamom, ginger, and Zaiqa special tea."
  }
];

export const menuItems: MenuItem[] = [
  {
    id: "velvety-shahi-handi",
    categoryId: "handi-karahi",
    name: "Velvety Shahi Handi",
    slug: "velvety-shahi-handi",
    description: "Creamy homemade chicken handi — choose Half or Full portion.",
    price: 1199,
    image: "/images/menu/shahi-handi-clean.webp",
    popular: true,
    tags: ["Gravy", "Best seller", "Dinner"],
    mealTime: "dinner",
    spiceLevel: "medium",
    prepTime: 40,
    available: true,
    optionsHint: "Half / Full",
    options: [
      { id: "half", label: "Half (500g)", price: 1199, hintLabel: "Half" },
      { id: "full", label: "Full (1kg)", price: 2199, hintLabel: "Full" }
    ]
  },

  {
    id: "royal-gola-kabab-half",
    categoryId: "handi-karahi",
    name: "Royal Gola Kabab Bowl Half",
    slug: "royal-gola-kabab-half",
    description: "Tender gola kabab in a rich creamy bowl, built for sharing.",
    price: 1299,
    image: "/images/menu/gola-kabab-clean.webp",
    popular: false,
    tags: ["Kabab", "Dinner"],
    mealTime: "dinner",
    spiceLevel: "medium",
    prepTime: 35,
    available: true
  },
  {
    id: "eco-crunch-patty-burger",
    categoryId: "crunchy-burger",
    name: "Eco Crunch Patty Burger",
    slug: "eco-crunch-patty-burger",
    description: "Juicy chicken breast with house-made sauce in a toasted bun.",
    price: 249,
    image: "/images/menu/eco-crunch.webp",
    popular: true,
    tags: ["Burger", "Crunchy", "Quick bite"],
    mealTime: "lunch",
    spiceLevel: "medium",
    prepTime: 18,
    available: true,
    variantLabel: "Crunchy Patty"
  },
  {
    id: "zinger-booster",
    categoryId: "crunchy-burger",
    name: "Zinger Booster",
    slug: "zinger-booster",
    description: "Crispy zinger chicken, lettuce, and creamy house sauce.",
    price: 299,
    image: "/images/menu/zinger-burger.webp",
    popular: true,
    tags: ["Zinger", "Best seller"],
    mealTime: "dinner",
    spiceLevel: "hot",
    prepTime: 20,
    available: true,
    variantLabel: "Zinger"
  },
  {
    id: "zaiqa-double-decker",
    categoryId: "crunchy-burger",
    name: "Zaiqa Double Decker",
    slug: "zaiqa-double-decker",
    description: "Two crispy zinger layers with cheese-style sauce and crunchy lettuce.",
    price: 599,
    image: "/images/menu/double-decker.webp",
    popular: false,
    tags: ["Burger", "Loaded", "Double Decker"],
    mealTime: "dinner",
    spiceLevel: "hot",
    prepTime: 24,
    available: true,
    variantLabel: "Double Decker"
  },
  {
    id: "zaiqa-chapligar",
    categoryId: "chapli-burgers",
    name: "Zaiqa Chapligar",
    slug: "zaiqa-chapligar",
    description: "Traditional chapli patty with fresh spices and house sauce.",
    price: 249,
    image: "/images/menu/burger-plate.webp",
    popular: false,
    tags: ["Burger", "Chapli", "Patty"],
    mealTime: "lunch",
    spiceLevel: "medium",
    prepTime: 18,
    available: true,
    variantLabel: "Single"
  },
  {
    id: "zaiqa-chapligar-twin-tower",
    categoryId: "chapli-burgers",
    name: "Zaiqa Chapligar Twin Tower",
    slug: "zaiqa-chapligar-twin-tower",
    description: "Double chapli patties stacked with cheese-style sauce and fresh toppings.",
    price: 449,
    image: "/images/menu/burger-plate.webp",
    popular: false,
    tags: ["Burger", "Chapli", "Twin Tower", "Double Patty"],
    mealTime: "dinner",
    spiceLevel: "medium",
    prepTime: 22,
    available: true,
    variantLabel: "Double/Twin Tower"
  },
  {
    id: "zaiqa-wrap",
    categoryId: "wraps",
    name: "Zaiqa Wrap",
    slug: "zaiqa-wrap",
    description: "Soft wrap packed with crispy chicken, greens, and house sauce.",
    price: 399,
    image: "/images/menu/wrap.webp",
    popular: false,
    tags: ["Wrap", "Lunch"],
    mealTime: "lunch",
    spiceLevel: "medium",
    prepTime: 18,
    available: true
  },
  {
    id: "king-crunch-wrap",
    categoryId: "wraps",
    name: "King Crunch Wrap",
    slug: "king-crunch-wrap",
    description: "A bigger wrap with extra crunch, sauce, and late-night energy.",
    price: 599,
    image: "/images/menu/wrap.webp",
    popular: true,
    tags: ["Wrap", "Popular", "Midnight"],
    mealTime: "dinner",
    spiceLevel: "hot",
    prepTime: 22,
    available: true
  },
  {
    id: "salty-plain-fries-half",
    categoryId: "appetizers",
    name: "Salty Plain Fries Half",
    slug: "salty-plain-fries-half",
    description: "Classic crisp fries, lightly salted — Half portion.",
    price: 199,
    image: "/images/menu/salty-plain-fries.webp",
    popular: false,
    tags: ["Fries", "Snack", "Half"],
    mealTime: "lunch",
    spiceLevel: "mild",
    prepTime: 14,
    available: true
  },
  {
    id: "salty-plain-fries-full",
    categoryId: "appetizers",
    name: "Salty Plain Fries Full",
    slug: "salty-plain-fries-full",
    description: "Classic crisp fries, lightly salted — Full portion.",
    price: 349,
    image: "/images/menu/salty-plain-fries.webp",
    popular: false,
    tags: ["Fries", "Snack", "Full"],
    mealTime: "lunch",
    spiceLevel: "mild",
    prepTime: 14,
    available: true
  },
  {
    id: "golden-hot-masala-fries-half",
    categoryId: "appetizers",
    name: "Golden Hot Masala Fries Half",
    slug: "golden-hot-masala-fries-half",
    description: "Crisp fries tossed in hot masala with house dip — Half portion.",
    price: 249,
    image: "/images/menu/masala-fries.webp",
    popular: true,
    tags: ["Fries", "Spicy", "Snack", "Half"],
    mealTime: "lunch",
    spiceLevel: "hot",
    prepTime: 14,
    available: true
  },
  {
    id: "golden-hot-masala-fries-full",
    categoryId: "appetizers",
    name: "Golden Hot Masala Fries Full",
    slug: "golden-hot-masala-fries-full",
    description: "Crisp fries tossed in hot masala with house dip — Full portion.",
    price: 349,
    image: "/images/menu/masala-fries.webp",
    popular: true,
    tags: ["Fries", "Spicy", "Snack", "Full"],
    mealTime: "lunch",
    spiceLevel: "hot",
    prepTime: 14,
    available: true
  },
  {
    id: "legend-loaded-fries-half",
    categoryId: "appetizers",
    name: "The Legend Loaded Fries Half",
    slug: "legend-loaded-fries-half",
    description: "Loaded fries layered with sauce, chicken bites, and spice — Half portion.",
    price: 299,
    image: "/images/menu/loaded-fries.webp",
    popular: true,
    tags: ["Loaded", "Best seller", "Half"],
    mealTime: "lunch",
    spiceLevel: "hot",
    prepTime: 18,
    available: true
  },
  {
    id: "legend-loaded-fries-full",
    categoryId: "appetizers",
    name: "The Legend Loaded Fries Full",
    slug: "legend-loaded-fries-full",
    description: "Loaded fries layered with sauce, chicken bites, and spice — Full portion.",
    price: 499,
    image: "/images/menu/loaded-fries.webp",
    popular: true,
    tags: ["Loaded", "Best seller", "Full"],
    mealTime: "lunch",
    spiceLevel: "hot",
    prepTime: 18,
    available: true
  },
  {
    id: "creamy-silky-pasta-half",
    categoryId: "appetizers",
    name: "Creamy Silky Pasta Half",
    slug: "creamy-silky-pasta-half",
    description: "Creamy silky pasta with rich white sauce — Half portion.",
    price: 299,
    image: "/images/menu/burger-plate.webp",
    popular: false,
    tags: ["Pasta", "Creamy", "Half"],
    mealTime: "lunch",
    spiceLevel: "mild",
    prepTime: 20,
    available: true
  },
  {
    id: "creamy-silky-pasta-full",
    categoryId: "appetizers",
    name: "Creamy Silky Pasta Full",
    slug: "creamy-silky-pasta-full",
    description: "Creamy silky pasta with rich white sauce — Full portion.",
    price: 549,
    image: "/images/menu/burger-plate.webp",
    popular: false,
    tags: ["Pasta", "Creamy", "Full"],
    mealTime: "lunch",
    spiceLevel: "mild",
    prepTime: 25,
    available: true
  },
  {
    id: "creamy-spicy-pasta-half",
    categoryId: "appetizers",
    name: "Creamy Spicy Pasta Half",
    slug: "creamy-spicy-pasta-half",
    description: "Creamy spicy pasta with bold flavors — Half portion.",
    price: 299,
    image: "/images/menu/burger-plate.webp",
    popular: false,
    tags: ["Pasta", "Spicy", "Half"],
    mealTime: "lunch",
    spiceLevel: "hot",
    prepTime: 20,
    available: true
  },
  {
    id: "creamy-spicy-pasta-full",
    categoryId: "appetizers",
    name: "Creamy Spicy Pasta Full",
    slug: "creamy-spicy-pasta-full",
    description: "Creamy spicy pasta with bold flavors — Full portion.",
    price: 549,
    image: "/images/menu/burger-plate.webp",
    popular: false,
    tags: ["Pasta", "Spicy", "Full"],
    mealTime: "lunch",
    spiceLevel: "hot",
    prepTime: 25,
    available: true
  },
  {
    id: "injected-nuggets-3pc",
    categoryId: "appetizers",
    name: "Injected Nuggets 3 Pieces",
    slug: "injected-nuggets-3pc",
    description: "Al-Baik style injected nuggets, crisp and tender — 3 pieces.",
    price: 249,
    image: "/images/menu/nuggets.webp",
    popular: false,
    tags: ["Nuggets", "Injected", "Kids", "3 Pcs"],
    mealTime: "lunch",
    spiceLevel: "mild",
    prepTime: 16,
    available: true
  },
  {
    id: "injected-nuggets-6pc",
    categoryId: "appetizers",
    name: "Injected Nuggets 6 Pieces",
    slug: "injected-nuggets-6pc",
    description: "Al-Baik style injected nuggets, crisp and tender — 6 pieces.",
    price: 449,
    image: "/images/menu/nuggets.webp",
    popular: false,
    tags: ["Nuggets", "Injected", "Kids", "6 Pcs"],
    mealTime: "lunch",
    spiceLevel: "mild",
    prepTime: 16,
    available: true
  },
  {
    id: "injected-nuggets-12pc",
    categoryId: "appetizers",
    name: "Injected Nuggets 12 Pieces",
    slug: "injected-nuggets-12pc",
    description: "Al-Baik style injected nuggets, crisp and tender — 12 pieces.",
    price: 899,
    image: "/images/menu/nuggets.webp",
    popular: false,
    tags: ["Nuggets", "Injected", "Shareable", "12 Pcs"],
    mealTime: "lunch",
    spiceLevel: "mild",
    prepTime: 18,
    available: true
  },
  {
    id: "tempura-nuggets-4pc",
    categoryId: "appetizers",
    name: "Tempura Nuggets 4 Pieces",
    slug: "tempura-nuggets-4pc",
    description: "Skin-on tempura nuggets with a light crunchy coating — 4 pieces.",
    price: 249,
    image: "/images/menu/nuggets.webp",
    popular: false,
    tags: ["Nuggets", "Tempura", "Skin-on", "4 Pcs"],
    mealTime: "lunch",
    spiceLevel: "mild",
    prepTime: 16,
    available: true
  },
  {
    id: "tempura-nuggets-8pc",
    categoryId: "appetizers",
    name: "Tempura Nuggets 8 Pieces",
    slug: "tempura-nuggets-8pc",
    description: "Skin-on tempura nuggets with a light crunchy coating — 8 pieces.",
    price: 549,
    image: "/images/menu/nuggets.webp",
    popular: false,
    tags: ["Nuggets", "Tempura", "Skin-on", "8 Pcs"],
    mealTime: "lunch",
    spiceLevel: "mild",
    prepTime: 16,
    available: true
  },
  {
    id: "tempura-nuggets-12pc",
    categoryId: "appetizers",
    name: "Tempura Nuggets 12 Pieces",
    slug: "tempura-nuggets-12pc",
    description: "Skin-on tempura nuggets with a light crunchy coating — 12 pieces.",
    price: 849,
    image: "/images/menu/nuggets.webp",
    popular: false,
    tags: ["Nuggets", "Tempura", "Skin-on", "Shareable", "12 Pcs"],
    mealTime: "lunch",
    spiceLevel: "mild",
    prepTime: 18,
    available: true
  },
  {
    id: "crispy-chicken-strips-4pc",
    categoryId: "appetizers",
    name: "Crispy Chicken Strips 4 Pieces",
    slug: "crispy-chicken-strips-4pc",
    description: "Crispy golden chicken strips with dipping sauce — 4 pieces.",
    price: 399,
    image: "/images/menu/chicken-strips.webp",
    popular: false,
    tags: ["Strips", "Crispy", "4 Pcs"],
    mealTime: "lunch",
    spiceLevel: "medium",
    prepTime: 18,
    available: true
  },
  {
    id: "crispy-chicken-strips-8pc",
    categoryId: "appetizers",
    name: "Crispy Chicken Strips 8 Pieces",
    slug: "crispy-chicken-strips-8pc",
    description: "Crispy golden chicken strips with dipping sauce — 8 pieces.",
    price: 749,
    image: "/images/menu/chicken-strips.webp",
    popular: false,
    tags: ["Strips", "Crispy", "Shareable", "8 Pcs"],
    mealTime: "lunch",
    spiceLevel: "medium",
    prepTime: 20,
    available: true
  },
  {
    id: "dip-sauce",
    categoryId: "appetizers",
    name: "Dip Sauce",
    slug: "dip-sauce",
    description: "House-made dipping sauce for nuggets, strips, and fries.",
    price: 69,
    image: "/images/menu/nuggets.webp",
    popular: false,
    tags: ["Dip", "Sauce", "Add-on"],
    mealTime: "lunch",
    spiceLevel: "mild",
    prepTime: 5,
    available: true
  },
  {
    id: "chunky-chicken-12pc",
    categoryId: "chunky-chicken",
    name: "Chunky Chicken 12 Pieces",
    slug: "chunky-chicken-12pc",
    description: "Twelve crispy chicken chunks with a dipping sauce.",
    price: 499,
    image: "/images/menu/chunky-chicken.webp",
    popular: true,
    tags: ["Chunky", "Shareable", "12 Pcs"],
    mealTime: "lunch",
    spiceLevel: "medium",
    prepTime: 20,
    available: true
  },
  {
    id: "masala-wings",
    categoryId: "wings",
    name: "Masala Wings",
    slug: "masala-wings",
    description: "with green chutney",
    price: 449,
    image: "/images/menu/baked-wings.webp",
    popular: true,
    tags: ["Wings", "Masala", "Green Chutney"],
    mealTime: "dinner",
    spiceLevel: "hot",
    prepTime: 22,
    available: true
  },
  {
    id: "plain-baked-wings",
    categoryId: "wings",
    name: "Plain Baked Wings",
    slug: "plain-baked-wings",
    description: "plain",
    price: 449,
    image: "/images/menu/baked-wings.webp",
    popular: false,
    tags: ["Wings", "Baked", "Plain"],
    mealTime: "dinner",
    spiceLevel: "medium",
    prepTime: 22,
    available: true
  },
  {
    id: "solo-handi-deal",
    categoryId: "deals",
    name: "Solo Handi Deal",
    slug: "solo-handi-deal",
    description: "Quarter Handi (250g) + 2 Milky Naan + 1 Buddy Drink (350ml).",
    price: 649,
    image: "/images/menu/shahi-handi-clean.webp",
    popular: true,
    tags: ["Deal", "Solo", "Handi", "Naan", "Drink"],
    mealTime: "dinner",
    spiceLevel: "medium",
    prepTime: 32,
    available: true,
    handi_quantity: 1,
    handi_size: "250g",
    appetizer_count: 0,
    appetizer_types: [],
    naan_quantity: 2,
    drink_volume_liters: 0.35,
    free_items: []
  },
  {
    id: "solo-zinger-deal",
    categoryId: "deals",
    name: "Solo Zinger Deal",
    slug: "solo-zinger-deal",
    description: "1 Zinger Booster + Half Golden Hot Masala Fries + 1 Drink (350ml).",
    price: 549,
    image: "/images/menu/zinger-burger.webp",
    popular: true,
    tags: ["Deal", "Solo", "Zinger", "Fries", "Drink"],
    mealTime: "dinner",
    spiceLevel: "hot",
    prepTime: 22,
    available: true,
    handi_quantity: 0,
    handi_size: "",
    appetizer_count: 1,
    appetizer_types: ["Golden Hot Masala Fries (Half)"],
    naan_quantity: 0,
    drink_volume_liters: 0.35,
    free_items: []
  },
  {
    id: "happy-family-deal",
    categoryId: "deals",
    name: "Happy Family Deal",
    slug: "happy-family-deal",
    description: "Half Velvety Shahi Handi (500g) + 8 Injected Nuggets + 12 Baked Wings + 6 Milky Naan + 1.5 Ltr Drink + Free Zinger Booster.",
    price: 2899,
    image: "/images/menu/shahi-handi-clean.webp",
    popular: true,
    tags: ["Deal", "Family", "Handi", "Nuggets", "Wings", "Naan", "Drink", "Free Zinger"],
    mealTime: "dinner",
    spiceLevel: "medium",
    prepTime: 48,
    available: true,
    handi_quantity: 1,
    handi_size: "500g",
    appetizer_count: 20,
    appetizer_types: ["Injected Nuggets", "Baked Wings"],
    naan_quantity: 6,
    drink_volume_liters: 1.5,
    free_items: ["Zinger Booster"]
  },
  {
    id: "buddy-deal",
    categoryId: "deals",
    name: "Buddy Deal",
    slug: "buddy-deal",
    description: "2 Zinger Boosters + Half Golden Hot Masala Fries + 2 Buddy Drinks (350ml each).",
    price: 949,
    image: "/images/menu/zinger-burger.webp",
    popular: false,
    tags: ["Deal", "Two people", "Zinger", "Fries", "Drinks"],
    mealTime: "dinner",
    spiceLevel: "hot",
    prepTime: 28,
    available: true,
    handi_quantity: 0,
    handi_size: "",
    appetizer_count: 1,
    appetizer_types: ["Golden Hot Masala Fries (Half)"],
    naan_quantity: 0,
    drink_volume_liters: 0.7,
    free_items: []
  },
  {
    id: "midnight-sharing-deal",
    categoryId: "deals",
    name: "Midnight Sharing Deal",
    slug: "midnight-sharing-deal",
    description: "2 Zaiqa Wraps + 2 Buddy Drinks (350ml each). Available 11 PM to 1 AM.",
    price: 949,
    image: "/images/menu/wrap.webp",
    popular: false,
    tags: ["Deal", "Midnight", "Shareable", "Wrap", "Drinks"],
    mealTime: "dinner",
    spiceLevel: "medium",
    prepTime: 24,
    available: true,
    handi_quantity: 0,
    handi_size: "",
    appetizer_count: 0,
    appetizer_types: [],
    naan_quantity: 0,
    drink_volume_liters: 0.7,
    free_items: []
  },
  {
    id: "couple-deal",
    categoryId: "deals",
    name: "Couple Deal",
    slug: "couple-deal",
    description: "2 Tempura Nuggets (4pc each) + 2 Injected Nuggets (3pc each) + 4 Baked Wings + Regular Salty Plain Fries (Half) + 2 Karak Doodh Patti or Drinks.",
    price: 899,
    image: "/images/menu/nuggets.webp",
    popular: false,
    tags: ["Deal", "Couple", "Nuggets", "Wings", "Fries", "Tea", "Drink"],
    mealTime: "dinner",
    spiceLevel: "medium",
    prepTime: 30,
    available: true,
    handi_quantity: 0,
    handi_size: "",
    appetizer_count: 4,
    appetizer_types: [
      "Tempura Nuggets (4pc) x2",
      "Injected Nuggets (3pc) x2",
      "Baked Wings x4",
      "Salty Plain Fries (Half) x1"
    ],
    naan_quantity: 0,
    drink_volume_liters: 0.7,
    free_items: []
  },
  {
    id: "milky-naan",
    categoryId: "breads-drinks",
    name: "Milky Naan",
    slug: "milky-naan",
    description: "Soft naan for pairing with handi and karahi orders.",
    price: 50,
    image: "/images/menu/milky-naan.webp",
    popular: false,
    tags: ["Bread", "Add-on", "Naan"],
    mealTime: "dinner",
    spiceLevel: "mild",
    prepTime: 8,
    available: true
  },
  {
    id: "drink-350ml",
    categoryId: "breads-drinks",
    name: "Drink (350ml)",
    slug: "drink-350ml",
    description: "Cold soft drink in a 350ml bottle.",
    price: 80,
    image: "/images/menu/elaichi-chai.webp",
    popular: false,
    tags: ["Drink", "Cold", "Add-on"],
    mealTime: "lunch",
    spiceLevel: "mild",
    prepTime: 2,
    available: true
  },
  {
    id: "zaiqa-doodh-patti",
    categoryId: "tea",
    name: "Zaiqa Doodh Patti",
    slug: "zaiqa-doodh-patti",
    description: "Rich karak doodh patti brewed with milk and tea leaves.",
    price: 120,
    image: "/images/menu/elaichi-chai.webp",
    popular: false,
    tags: ["Tea", "Doodh Patti", "Karak", "Hot"],
    mealTime: "beverages",
    spiceLevel: "mild",
    prepTime: 10,
    available: true
  },
  {
    id: "cardamom-tea",
    categoryId: "tea",
    name: "Cardamom Tea",
    slug: "cardamom-tea",
    description: "Warm cardamom chai for pickup or evening delivery orders.",
    price: 120,
    image: "/images/menu/elaichi-chai.webp",
    popular: false,
    tags: ["Tea", "Cardamom", "Chai", "Hot"],
    mealTime: "beverages",
    spiceLevel: "mild",
    prepTime: 10,
    available: true
  },
  {
    id: "zaiqa-tea",
    categoryId: "tea",
    name: "Zaiqa Tea",
    slug: "zaiqa-tea",
    description: "Zaiqa special tea with a unique house blend.",
    price: 120,
    image: "/images/menu/elaichi-chai.webp",
    popular: false,
    tags: ["Tea", "Special", "Zaiqa", "Hot"],
    mealTime: "beverages",
    spiceLevel: "mild",
    prepTime: 10,
    available: true
  },
  {
    id: "ginger-tea",
    categoryId: "tea",
    name: "Ginger Tea",
    slug: "ginger-tea",
    description: "Fresh ginger tea with a warm, spicy kick.",
    price: 120,
    image: "/images/menu/elaichi-chai.webp",
    popular: false,
    tags: ["Tea", "Ginger", "Chai", "Hot"],
    mealTime: "beverages",
    spiceLevel: "mild",
    prepTime: 10,
    available: true
  }
];

export const deliveryAreas: DeliveryArea[] = [
  {
    id: "near-kitchen",
    name: "Near kitchen / Shah Rukn E Alam",
    fee: 80,
    eta: "20-30 min",
    minimumOrder: 499,
    active: true
  },
  {
    id: "gulgasht-bosan",
    name: "Gulgasht / Bosan Road",
    fee: 120,
    eta: "30-40 min",
    minimumOrder: 599,
    active: true
  },
  {
    id: "multan-cantt",
    name: "Cantt / Multan City",
    fee: 150,
    eta: "35-45 min",
    minimumOrder: 699,
    active: true
  },
  {
    id: "wapda-bahadurpur",
    name: "WAPDA Town / Bahadurpur",
    fee: 180,
    eta: "40-50 min",
    minimumOrder: 799,
    active: true
  },
  {
    id: "other-area",
    name: "Other Multan area - confirm on WhatsApp",
    fee: 0,
    eta: "Delivery fee confirmed on WhatsApp",
    minimumOrder: 0,
    active: true
  },
  {
    id: "pickup",
    name: "Pickup - Zaiqa Junction With Zahra's",
    fee: 0,
    eta: "Ready in 20-30 min",
    minimumOrder: 0,
    active: true
  }
];

export const reviews: Review[] = [
  {
    id: "review-1",
    name: "Areeba K.",
    rating: 5,
    quote: "The Shahi Handi tasted homemade but packed like a premium order. Naan arrived soft and warm.",
    source: "WhatsApp",
    image: "/images/menu/shahi-handi-clean.webp",
    createdAt: "2026-05-29T18:45:00.000Z",
    approved: true
  },
  {
    id: "review-2",
    name: "Hamza M.",
    rating: 5,
    quote: "Zinger Booster and loaded fries were better than my usual delivery app order. Direct WhatsApp confirmation was fast.",
    source: "Website",
    image: "/images/menu/zinger-burger.webp",
    createdAt: "2026-05-31T21:10:00.000Z",
    approved: true
  },
  {
    id: "review-3",
    name: "Nimra S.",
    rating: 5,
    quote: "Family deal was enough for everyone and the gravy had that fresh kitchen flavor.",
    source: "Foodpanda",
    image: "/images/menu/shahi-handi-clean.webp",
    createdAt: "2026-06-02T20:18:00.000Z",
    approved: true
  },
  {
    id: "review-4",
    name: "Bilal R.",
    rating: 4,
    quote: "Masala fries were crisp, spicy, and still hot when delivered. Will order again.",
    source: "Instagram",
    image: "/images/menu/masala-fries.webp",
    createdAt: "2026-06-03T23:35:00.000Z",
    approved: true
  }
];

export const seedOrders: Order[] = [
  {
    id: "ZQ-DEMO-101",
    customerName: "Demo Customer",
    phone: "0312-0000000",
    address: "Shah Rukn E Alam Town, Multan",
    deliveryAreaId: "near-kitchen",
    deliveryAreaName: "Near kitchen / Shah Rukn E Alam",
    deliveryFee: 120,
    items: [
      {
        lineId: "demo-1",
        menuItemId: "zinger-booster",
        name: "Zinger Booster",
        basePrice: 299,
        price: 299,
        quantity: 2,
        addons: []
      },
      {
        lineId: "demo-2",
        menuItemId: "legend-loaded-fries-full",
        name: "The Legend Loaded Fries Full",
        basePrice: 499,
        price: 499,
        quantity: 1,
        addons: []
      }
    ],
    subtotal: 1097,
    discount: 0,
    total: 1217,
    loyaltyPointsEarned: 12,
    paymentMethod: "cash_on_delivery",
    status: "preparing",
    createdAt: "2026-06-05T17:45:00.000Z"
  }
];